# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle Selenium and Cucumber

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

env:
  headless: true

jobs:
  build:
    runs-on: ubuntu-latest # Using linux machine
    steps:
    - uses: actions/checkout@v3 # Checkout the code
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Install Google Chrome # Using shell script to install Google Chrome
      run: |
       chmod +x ./scripts/chrome.sh
        ./scripts/chrome.sh
    - name: Grant execute permission for chromeDriver
      run: chmod +x webdrivers/linux/chromedriver
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew # give permission to Gradle to run the commands
    - name: Build with Gradle
      run: ./gradlew test cucumber
